name = "QL Pack"
grammar = "yaml"
path_suffixes = ["qlpack.yml", "qlpack.yaml", "codeql-workspace.yml"]
line_comments = ["#"]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = false }
]
auto_pairs = [
    { start = "{", end = "}" },
    { start = "[", end = "]" },
    { start = "\"", end = "\"" },
    { start = "'", end = "'" }
]