id = "codeql"
name = "CodeQL"
description = "CodeQL language support and query execution for Zed"
version = "0.1.0"
schema_version = 1
authors = ["blacktop"]
repository = "https://github.com/blacktop/zed-codeql"

[language_servers.codeql]
name = "codeql"
languages = ["CodeQL"]

[grammars.ql]
repository = "https://github.com/tree-sitter/tree-sitter-ql"
commit = "bd087020f0d8c183080ca615d38de0ec827aeeaf"

[grammars.yaml]
repository = "https://github.com/tree-sitter/tree-sitter-yaml"
