id = "codeql"
name = "CodeQL"
description = "CodeQL language support with syntax highlighting and language server for Zed"
version = "0.1.0"
schema_version = 1
authors = ["blacktop"]
repository = "https://github.com/blacktop/zed-codeql"

[language_servers.codeql]
name = "codeql"
languages = ["CodeQL"]

[grammars.ql]
repository = "https://github.com/tree-sitter/tree-sitter-ql"
commit = "1fd627a4e8bff8c24c11987474bd33112bead857"
